field: 65aebe37-64ef-44f7-85e2-55b1788e8ebd
fieldLayouts:
  5e1ddad6-5c6a-466a-a340-1e9e283a8b25:
    tabs:
      -
        elements:
          -
            fieldUid: 5f888b63-f0b9-4647-92f5-ced1232a6941
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 2862efef-057b-4a02-a887-57f77dd7b564
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 3bfd5985-56cc-43e0-984c-770fdcefda61
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 01487a7f-4903-46f2-a5b0-5924c5685e25
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 303dcdec-2176-4fa7-887f-18f59505e244
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: a4a137d8-5552-460d-8e40-6145a2bb9b86
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: a96a311b-81f3-40c8-81d7-2bc536cd7b40
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 496b2a82-24a6-4d0f-9d77-e3c185dfa0e0
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: fb72befd-3dc3-446c-874b-5ee205bb23ca
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  01487a7f-4903-46f2-a5b0-5924c5685e25:
    contentColumnType: text
    fieldGroup: null
    handle: cardButton
    instructions: ''
    name: 'Card button'
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: text
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  2862efef-057b-4a02-a887-57f77dd7b564:
    contentColumnType: string
    fieldGroup: null
    handle: cardImage
    instructions: ''
    name: 'Card image'
    searchable: true
    settings:
      allowSelfRelations: false
      allowedKinds: null
      defaultUploadLocationSource: 'volume:528b0d00-159a-4866-aca8-d9394e99bb05'
      defaultUploadLocationSubpath: ''
      limit: ''
      localizeRelations: false
      restrictFiles: ''
      selectionLabel: ''
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: true
      singleUploadLocationSource: 'volume:528b0d00-159a-4866-aca8-d9394e99bb05'
      singleUploadLocationSubpath: ''
      source: null
      sources:
        - 'volume:528b0d00-159a-4866-aca8-d9394e99bb05'
      targetSiteId: null
      useSingleFolder: false
      validateRelatedElements: false
      viewMode: large
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  303dcdec-2176-4fa7-887f-18f59505e244:
    contentColumnType: text
    fieldGroup: null
    handle: cardButtonCustomLink
    instructions: 'Use this to add custom offsite url'
    name: 'Card button custom link'
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: text
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  3bfd5985-56cc-43e0-984c-770fdcefda61:
    contentColumnType: text
    fieldGroup: null
    handle: cardText
    instructions: ''
    name: 'Card text'
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: text
      initialRows: '4'
      multiline: '1'
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  496b2a82-24a6-4d0f-9d77-e3c185dfa0e0:
    contentColumnType: string
    fieldGroup: null
    handle: exampleLinks
    instructions: 'Use this to link to a couple of examples relevant to the content'
    name: 'Example links'
    searchable: true
    settings:
      allowSelfRelations: false
      limit: ''
      localizeRelations: false
      selectionLabel: ''
      showSiteMenu: true
      source: null
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Entries
  5f888b63-f0b9-4647-92f5-ced1232a6941:
    contentColumnType: text
    fieldGroup: null
    handle: cardTitle
    instructions: ''
    name: 'Card title'
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: text
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  a4a137d8-5552-460d-8e40-6145a2bb9b86:
    contentColumnType: string
    fieldGroup: null
    handle: cardButtonLink
    instructions: ''
    name: 'Card button link'
    searchable: true
    settings:
      allowSelfRelations: false
      limit: ''
      localizeRelations: false
      selectionLabel: ''
      showSiteMenu: true
      source: null
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Entries
  a96a311b-81f3-40c8-81d7-2bc536cd7b40:
    contentColumnType: text
    fieldGroup: null
    handle: linksHeading
    instructions: ''
    name: 'Links heading'
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: text
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  fb72befd-3dc3-446c-874b-5ee205bb23ca:
    contentColumnType: string
    fieldGroup: null
    handle: customLinks
    instructions: ''
    name: 'Custom links'
    searchable: true
    settings:
      columns:
        241:
          __assoc__:
            -
              - width
              - ''
        242:
          __assoc__:
            -
              - width
              - ''
      contentTable: '{{%stc_customlinks}}'
      fieldLayout: row
      maxRows: '2'
      minRows: ''
      placeholderKey: null
      propagationMethod: all
      selectionLabel: 'Add custom example links'
      staticField: ''
    translationKeyFormat: null
    translationMethod: site
    type: verbb\supertable\fields\SuperTableField
handle: cardImageTop
name: 'Card image top'
sortOrder: 1
