field: 4d97bb57-65e2-4a24-a25f-de74c14bb806
fieldLayouts:
  9e34fbec-4e5c-4f60-9445-a14c82b0db7d:
    tabs:
      -
        elements:
          -
            fieldUid: 0aab1fd2-8906-4b68-ae49-e86e9f40be6d
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  0aab1fd2-8906-4b68-ae49-e86e9f40be6d:
    contentColumnType: text
    fieldGroup: null
    handle: copyright
    instructions: ''
    name: Copyright
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: text
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: copyright
name: Copyright
sortOrder: 1
