field: 8a2aa11b-b2db-4cc2-9c6c-25d99ddb3913
fieldLayouts:
  4b7ffb93-8faf-40b1-91c8-6e3ff4aeb00a:
    tabs:
      -
        elements:
          -
            fieldUid: b5fb5f11-8dcf-4ed0-9e7f-44fa8acb3c82
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  b5fb5f11-8dcf-4ed0-9e7f-44fa8acb3c82:
    contentColumnType: string
    fieldGroup: null
    handle: callsToAction
    instructions: 'Select which actions you want to appear'
    name: 'Calls to action'
    searchable: false
    settings:
      multi: true
      options:
        -
          __assoc__:
            -
              - label
              - Chat
            -
              - value
              - chat
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Email
            -
              - value
              - email
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Phone
            -
              - value
              - phone
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Callback
            -
              - value
              - callback
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Checkboxes
handle: cta
name: CTA
sortOrder: 7
