field: fb82ef36-0c40-4f24-a454-7140f2da98ca
fieldLayouts:
  aa61689e-921f-406f-ac7e-22ccd25e8ee8:
    tabs:
      -
        elements:
          -
            fieldUid: 2050e617-3379-4055-92a5-db2dd43f8eee
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 51228c2c-6771-4288-b8fa-4f9c1e2f0da9
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 75f22887-c825-4075-958b-9c96e74a4567
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 0984d2d0-6cf3-4fbe-b23c-253b7e9381a5
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  0984d2d0-6cf3-4fbe-b23c-253b7e9381a5:
    contentColumnType: text
    fieldGroup: null
    handle: phone
    instructions: ''
    name: Phone
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  2050e617-3379-4055-92a5-db2dd43f8eee:
    contentColumnType: text
    fieldGroup: null
    handle: chat
    instructions: 'add chat domain'
    name: Chat
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: yachtcrewhelp.org
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  51228c2c-6771-4288-b8fa-4f9c1e2f0da9:
    contentColumnType: text
    fieldGroup: null
    handle: email
    instructions: 'add email to produce automatic mail to link'
    name: Email
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  75f22887-c825-4075-958b-9c96e74a4567:
    contentColumnType: string
    fieldGroup: null
    handle: callback
    instructions: 'Add link to callback page'
    name: Callback
    searchable: false
    settings:
      allowSelfRelations: false
      limit: ''
      localizeRelations: false
      selectionLabel: ''
      showSiteMenu: true
      source: null
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Entries
handle: ctaBlock
name: 'CTA Block'
sortOrder: 1
