field: 8a2aa11b-b2db-4cc2-9c6c-25d99ddb3913
fieldLayouts:
  b6c6baff-34df-4675-b2aa-3e73d3865261:
    tabs:
      -
        elements:
          -
            fieldUid: 957da3ea-21f1-4493-a9ad-e0779c39ca26
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 0dc8a341-8175-4d32-8de4-06b280e0ef2a
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: ff135204-13af-48d7-9b1d-c82cd47cf2eb
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 4443e604-b1b9-423f-82bd-880a43c8a595
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  0dc8a341-8175-4d32-8de4-06b280e0ef2a:
    contentColumnType: text
    fieldGroup: null
    handle: subline
    instructions: 'small amount of text to appear under heading if required - use for short explanations'
    name: Subline
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: text
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  4443e604-b1b9-423f-82bd-880a43c8a595:
    contentColumnType: string
    fieldGroup: null
    handle: displayStyle
    instructions: 'Sets display style for document list'
    name: 'Display style'
    searchable: true
    settings:
      optgroups: true
      options:
        -
          __assoc__:
            -
              - label
              - 'Box list'
            -
              - value
              - boxList
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'Icon list'
            -
              - value
              - iconList
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'Button list'
            -
              - value
              - buttonList
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
  957da3ea-21f1-4493-a9ad-e0779c39ca26:
    contentColumnType: text
    fieldGroup: null
    handle: heading
    instructions: 'heading to show above download(s)'
    name: Heading
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: text
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  ff135204-13af-48d7-9b1d-c82cd47cf2eb:
    contentColumnType: string
    fieldGroup: null
    handle: download
    instructions: ''
    name: Download
    searchable: true
    settings:
      allowSelfRelations: false
      allowUploads: true
      allowedKinds: null
      defaultUploadLocationSource: 'volume:bccbe5e7-459a-476e-905c-a93ac10b478b'
      defaultUploadLocationSubpath: ''
      limit: ''
      localizeRelations: false
      previewMode: full
      restrictFiles: ''
      selectionLabel: 'Choose a file to add'
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: true
      singleUploadLocationSource: 'volume:528b0d00-159a-4866-aca8-d9394e99bb05'
      singleUploadLocationSubpath: ''
      source: null
      sources: '*'
      targetSiteId: null
      useSingleFolder: false
      validateRelatedElements: false
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
handle: downloads
name: Downloads
sortOrder: 6
