field: 4d97bb57-65e2-4a24-a25f-de74c14bb806
fieldLayouts:
  e428886b-2181-4342-b94c-1437f296ecee:
    tabs:
      -
        elements:
          -
            fieldUid: f7d0a984-acb2-4bd7-8240-59eab595b89d
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  f7d0a984-acb2-4bd7-8240-59eab595b89d:
    contentColumnType: string
    fieldGroup: null
    handle: footerRightLink
    instructions: ''
    name: 'Footer right link'
    searchable: true
    settings:
      allowSelfRelations: false
      limit: ''
      localizeRelations: false
      selectionLabel: ''
      showSiteMenu: true
      source: null
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Entries
handle: footerRightLinks
name: 'Footer right links'
sortOrder: 3
