field: 01d3d205-50b0-445d-952a-1dca0c3c0061
fieldLayouts:
  cb468e49-125c-4ebc-8f83-d6fd354764bc:
    tabs:
      -
        elements:
          -
            fieldUid: 8fa54438-1f95-4c42-ba36-2ae661ab1811
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  8fa54438-1f95-4c42-ba36-2ae661ab1811:
    contentColumnType: string
    fieldGroup: null
    handle: footerLeftLink
    instructions: ''
    name: 'Footer left link'
    searchable: true
    settings:
      allowSelfRelations: false
      limit: ''
      localizeRelations: false
      selectionLabel: ''
      showSiteMenu: true
      source: null
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Entries
handle: footerLeftLinks
name: 'Footer left links'
sortOrder: 2
