field: 4d97bb57-65e2-4a24-a25f-de74c14bb806
fieldLayouts:
  9fd9f2cb-24dd-427a-b0f3-e69c06db9a5b:
    tabs:
      -
        elements:
          -
            fieldUid: ddabdb38-40a0-4b9b-a77c-237c5e452c47
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  ddabdb38-40a0-4b9b-a77c-237c5e452c47:
    contentColumnType: string
    fieldGroup: null
    handle: footerLeftLink
    instructions: ''
    name: 'Footer left link'
    searchable: true
    settings:
      allowSelfRelations: false
      limit: ''
      localizeRelations: false
      selectionLabel: ''
      showSiteMenu: true
      source: null
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Entries
handle: footerLeftLinks
name: 'Footer left links'
sortOrder: 2
