field: 4d8e1527-deab-46a5-8302-623783913d20
fieldLayouts:
  5243dbd8-f206-45ff-ac5c-d4e52cf57ccd:
    tabs:
      -
        elements:
          -
            fieldUid: d2570f16-7a9e-4d8d-9af9-17372923f6c7
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 9f0c1a20-5b50-4304-b8bf-85f13791fe7a
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 4756c00f-8268-4b23-90fc-d55840b86e55
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 3d324029-3dc6-4a59-93fb-4a4c61136c6b
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  3d324029-3dc6-4a59-93fb-4a4c61136c6b:
    contentColumnType: string
    fieldGroup: null
    handle: buttonLink
    instructions: ''
    name: 'Button link'
    searchable: true
    settings:
      allowSelfRelations: false
      limit: ''
      localizeRelations: false
      selectionLabel: ''
      showSiteMenu: true
      source: null
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Entries
  4756c00f-8268-4b23-90fc-d55840b86e55:
    contentColumnType: text
    fieldGroup: null
    handle: buttonText
    instructions: ''
    name: 'Button text'
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: text
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  9f0c1a20-5b50-4304-b8bf-85f13791fe7a:
    contentColumnType: string
    fieldGroup: null
    handle: icons
    instructions: ''
    name: Icons
    searchable: true
    settings:
      columns:
        __assoc__:
          -
            - 108
            -
              __assoc__:
                -
                  - width
                  - ''
          -
            - 111
            -
              __assoc__:
                -
                  - width
                  - ''
          -
            - 112
            -
              __assoc__:
                -
                  - width
                  - ''
          -
            - 109
            -
              __assoc__:
                -
                  - width
                  - ''
          -
            - 110
            -
              __assoc__:
                -
                  - width
                  - ''
      contentTable: '{{%stc_icons}}'
      fieldLayout: row
      maxRows: ''
      minRows: ''
      placeholderKey: null
      propagationMethod: all
      selectionLabel: 'Add icon column'
      staticField: ''
    translationKeyFormat: null
    translationMethod: site
    type: verbb\supertable\fields\SuperTableField
  d2570f16-7a9e-4d8d-9af9-17372923f6c7:
    contentColumnType: text
    fieldGroup: null
    handle: heading
    instructions: ''
    name: Heading
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: text
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: iconRow
name: 'Icon row'
sortOrder: 1
