field: 8a2aa11b-b2db-4cc2-9c6c-25d99ddb3913
fieldLayouts:
  072d033e-7907-4961-8413-bc97468d6d58:
    tabs:
      -
        elements:
          -
            fieldUid: dec725ab-1bdc-4ef1-b754-4fdae22a1bad
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 6869de47-dc27-4046-9ae6-33fafd01b908
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 9b64ac14-7705-4b60-870d-8e7a0b2fd917
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  6869de47-dc27-4046-9ae6-33fafd01b908:
    contentColumnType: text
    fieldGroup: null
    handle: caption
    instructions: ''
    name: Caption
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: text
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  9b64ac14-7705-4b60-870d-8e7a0b2fd917:
    contentColumnType: text
    fieldGroup: null
    handle: imageLink
    instructions: 'You can add a link to the image. Add a full url for external images or a relative url for local links'
    name: 'Image link'
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  dec725ab-1bdc-4ef1-b754-4fdae22a1bad:
    contentColumnType: string
    fieldGroup: null
    handle: image
    instructions: ''
    name: Image
    searchable: true
    settings:
      allowSelfRelations: false
      allowedKinds: null
      defaultUploadLocationSource: 'volume:528b0d00-159a-4866-aca8-d9394e99bb05'
      defaultUploadLocationSubpath: ''
      limit: '1'
      localizeRelations: false
      restrictFiles: ''
      selectionLabel: ''
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: true
      singleUploadLocationSource: 'volume:528b0d00-159a-4866-aca8-d9394e99bb05'
      singleUploadLocationSubpath: ''
      source: null
      sources:
        - 'volume:528b0d00-159a-4866-aca8-d9394e99bb05'
        - 'volume:unsplashImages'
      targetSiteId: null
      useSingleFolder: false
      validateRelatedElements: false
      viewMode: large
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
handle: image
name: Image
sortOrder: 2
