field: 4d8e1527-deab-46a5-8302-623783913d20
fieldLayouts:
  d51cbcae-51c6-418e-83c0-83d0c32c68d1:
    tabs:
      -
        elements:
          -
            fieldUid: b250c29d-89a3-47e9-8814-4e3ad1c5d224
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: e08627f2-bf20-438b-b455-7a7f3051fb20
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: afee777a-fdbd-46e9-b57f-9b1e103b590d
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 555e3276-84c9-40b9-8c48-272022865157
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: b29804a1-4b02-4861-acaa-0f45e8ed9969
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: bdb68389-947a-4e95-8d08-235731870346
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 60f46ded-110e-4f3e-961b-0ad5a6c7fa6a
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 4948066d-1240-4a7d-8fac-c9b04cbefee1
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  4948066d-1240-4a7d-8fac-c9b04cbefee1:
    contentColumnType: text
    fieldGroup: null
    handle: authorRole
    instructions: ''
    name: 'Author role'
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: text
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  555e3276-84c9-40b9-8c48-272022865157:
    contentColumnType: string
    fieldGroup: null
    handle: buttonLink
    instructions: ''
    name: 'Button link'
    searchable: true
    settings:
      allowSelfRelations: false
      limit: ''
      localizeRelations: false
      selectionLabel: 'Link to an entry'
      showSiteMenu: true
      source: null
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Entries
  60f46ded-110e-4f3e-961b-0ad5a6c7fa6a:
    contentColumnType: text
    fieldGroup: null
    handle: author
    instructions: ''
    name: Author
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: text
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  afee777a-fdbd-46e9-b57f-9b1e103b590d:
    contentColumnType: text
    fieldGroup: null
    handle: intro
    instructions: ''
    name: Intro
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: text
      initialRows: '4'
      multiline: '1'
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  b250c29d-89a3-47e9-8814-4e3ad1c5d224:
    contentColumnType: text
    fieldGroup: null
    handle: contentType
    instructions: ''
    name: 'Content type'
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: text
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  b29804a1-4b02-4861-acaa-0f45e8ed9969:
    contentColumnType: text
    fieldGroup: null
    handle: buttonText
    instructions: ''
    name: 'Button text'
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: text
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  bdb68389-947a-4e95-8d08-235731870346:
    contentColumnType: text
    fieldGroup: null
    handle: quote
    instructions: ''
    name: Quote
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: text
      initialRows: '4'
      multiline: '1'
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  e08627f2-bf20-438b-b455-7a7f3051fb20:
    contentColumnType: text
    fieldGroup: null
    handle: rowTitle
    instructions: ''
    name: Title
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: text
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: quoteRow
name: 'Quote row'
sortOrder: 2
