field: a85f91d3-6437-4e05-8e0c-aca0a3be3e5d
fieldLayouts:
  3eb3d030-c04a-4a4c-bf99-225c96dd901e:
    tabs:
      -
        elements:
          -
            fieldUid: d9a6d503-a209-488b-aefe-2f59b9403a29
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 00656a77-5f71-4968-ae71-873c0e20b7db
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: eaaa4136-98fa-474f-8362-d08d11f02a76
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: a7df7184-ffa8-44e2-a567-d42249ff60fb
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 2c6a4b83-787a-4bce-8d7f-cd1f4d468539
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 1a79e2d6-ed94-4ea3-8593-de83ce84ea1b
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 6cef57f3-e94e-4810-9ae7-a0d294fd496f
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  00656a77-5f71-4968-ae71-873c0e20b7db:
    contentColumnType: text
    fieldGroup: null
    handle: category
    instructions: 'Tiny text indicating the type of content - eg if its a news item put ''news'''
    name: Category
    searchable: true
    settings:
      byteLimit: null
      charLimit: '10'
      code: ''
      columnType: text
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  1a79e2d6-ed94-4ea3-8593-de83ce84ea1b:
    contentColumnType: string
    fieldGroup: null
    handle: buttonLink
    instructions: ''
    name: 'Button link'
    searchable: true
    settings:
      allowSelfRelations: false
      limit: '1'
      localizeRelations: false
      selectionLabel: ''
      showSiteMenu: true
      source: null
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Entries
  2c6a4b83-787a-4bce-8d7f-cd1f4d468539:
    contentColumnType: text
    fieldGroup: null
    handle: buttonText
    instructions: ''
    name: 'Button text'
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: text
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  6cef57f3-e94e-4810-9ae7-a0d294fd496f:
    contentColumnType: string
    fieldGroup: null
    handle: position
    instructions: 'select a placement for the text box over the image'
    name: Position
    searchable: true
    settings:
      default: right
      options:
        __assoc__:
          -
            - left
            - '1'
          -
            - center
            - '1'
          -
            - right
            - '1'
          -
            - full
            - ''
          -
            - drop-left
            - '1'
          -
            - drop-right
            - '1'
    translationKeyFormat: null
    translationMethod: none
    type: rias\positionfieldtype\fields\Position
  a7df7184-ffa8-44e2-a567-d42249ff60fb:
    contentColumnType: text
    fieldGroup: null
    handle: intro
    instructions: ''
    name: Intro
    searchable: true
    settings:
      byteLimit: null
      charLimit: '160'
      code: ''
      columnType: text
      initialRows: '4'
      multiline: '1'
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  d9a6d503-a209-488b-aefe-2f59b9403a29:
    contentColumnType: string
    fieldGroup: null
    handle: image
    instructions: ''
    name: Image
    searchable: true
    settings:
      allowSelfRelations: false
      allowedKinds: null
      defaultUploadLocationSource: 'volume:528b0d00-159a-4866-aca8-d9394e99bb05'
      defaultUploadLocationSubpath: ''
      limit: '1'
      localizeRelations: false
      restrictFiles: ''
      selectionLabel: 'Add slide image'
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: true
      singleUploadLocationSource: 'volume:528b0d00-159a-4866-aca8-d9394e99bb05'
      singleUploadLocationSubpath: ''
      source: null
      sources:
        - 'volume:bannerImages'
      targetSiteId: null
      useSingleFolder: false
      validateRelatedElements: false
      viewMode: large
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  eaaa4136-98fa-474f-8362-d08d11f02a76:
    contentColumnType: text
    fieldGroup: null
    handle: slideTitle
    instructions: ''
    name: Title
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: text
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: slide
name: Slide
sortOrder: 1
