field: 0d17b66a-cd19-4df2-861a-90576664f74e
fieldLayouts:
  a4cd1506-8d07-459e-b6eb-0704fc464171:
    tabs:
      -
        elements:
          -
            fieldUid: b3cdf578-7f9a-4376-94f1-b87e9e24c41c
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  b3cdf578-7f9a-4376-94f1-b87e9e24c41c:
    contentColumnType: string
    fieldGroup: null
    handle: tickListItem
    instructions: ''
    name: 'Tick list item'
    searchable: true
    settings:
      columns:
        186:
          __assoc__:
            -
              - width
              - ''
      contentTable: '{{%stc_ticklistitem}}'
      fieldLayout: table
      maxRows: ''
      minRows: ''
      placeholderKey: null
      propagationMethod: all
      selectionLabel: ''
      staticField: ''
    translationKeyFormat: null
    translationMethod: site
    type: verbb\supertable\fields\SuperTableField
handle: ticklist
name: Ticklist
sortOrder: 1
