field: 8a2aa11b-b2db-4cc2-9c6c-25d99ddb3913
fieldLayouts:
  7ffb6733-833e-4d8f-a0e2-2bb4ce49fb3f:
    tabs:
      -
        elements:
          -
            fieldUid: 852d1b23-fc46-4506-87d1-5df093ae2f21
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: ca18236e-e848-475d-8898-4bf04e130099
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 4f7f38cd-7805-4044-bca1-07aa1cd81acd
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  4f7f38cd-7805-4044-bca1-07aa1cd81acd:
    contentColumnType: text
    fieldGroup: null
    handle: text
    instructions: 'simple short text explanation of this link'
    name: Text
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  852d1b23-fc46-4506-87d1-5df093ae2f21:
    contentColumnType: string
    fieldGroup: null
    handle: usefulLink
    instructions: 'add a link to one of the useful orgs listed - if not there then add it first ;)'
    name: 'Useful link'
    searchable: false
    settings:
      allowSelfRelations: false
      limit: ''
      localizeRelations: false
      selectionLabel: 'Add a link to a useful organisation relevant to the content'
      showSiteMenu: true
      source: null
      sources:
        - 'section:15eef50e-9647-44d4-aa25-93cd576fa59a'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Entries
  ca18236e-e848-475d-8898-4bf04e130099:
    contentColumnType: string(255)
    fieldGroup: null
    handle: externalLink
    instructions: 'if you have to link offsite.....link to an external organsiation'
    name: 'External link'
    searchable: false
    settings:
      maxLength: '255'
      placeholder: ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Url
handle: usefullinks
name: 'Useful links'
sortOrder: 8
