field: 8a2aa11b-b2db-4cc2-9c6c-25d99ddb3913
fieldLayouts:
  befe356a-db9f-4f9c-971b-a9796ae0ad9d:
    tabs:
      -
        elements:
          -
            fieldUid: 64dd7d0f-4a2f-4e8e-ba31-0d43b2e3165e
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  64dd7d0f-4a2f-4e8e-ba31-0d43b2e3165e:
    contentColumnType: text
    fieldGroup: null
    handle: video
    instructions: 'Add your embed code here'
    name: Video
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: text
      initialRows: '6'
      multiline: '1'
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: video
name: Video
sortOrder: 3
