fieldLayouts:
  80ff338a-11c7-443c-9235-2319be5d9a52:
    tabs:
      -
        elements:
          -
            fieldUid: 118e35c9-2543-4382-80aa-59987109b314
            instructions: 'Upload / choose a picture in landscape 2400 px wide'
            label: ''
            required: ''
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\EntryTitleField
            warning: null
            width: 100
          -
            fieldUid: 5c41bdef-bb14-4e77-a5d8-b77d58560134
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: ab1038d7-9433-4401-b13d-001163c38d42
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
      -
        elements:
          -
            fieldUid: 43321487-c0cf-4014-9c35-7d648822348c
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: SEO
        sortOrder: 2
      -
        elements:
          -
            fieldUid: e650f7b8-2ff8-4084-acc6-cb0d6178e82e
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: b5ed2835-508b-4d72-aa69-f9754f9cd275
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: 'Menu settings'
        sortOrder: 3
handle: listingPage
hasTitleField: true
name: 'Listing page'
section: 7135d77d-f5e7-4d12-9d35-0c6e40777ee2
sortOrder: 5
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
