fieldLayouts:
  c3ab9e01-bb26-4110-a81d-c87f4277d61a:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\EntryTitleField
            warning: null
            width: 100
          -
            fieldUid: ab1038d7-9433-4401-b13d-001163c38d42
            instructions: 'Used in listing cards'
            label: ''
            required: ''
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 4c78bef1-0358-4ca8-a5d8-9112a3311aee
            instructions: 'Image will be used in listing page. Use content block image for in page image'
            label: ''
            required: ''
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 8a2aa11b-b2db-4cc2-9c6c-25d99ddb3913
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
      -
        elements:
          -
            fieldUid: 43321487-c0cf-4014-9c35-7d648822348c
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: SEO
        sortOrder: 2
      -
        elements:
          -
            fieldUid: e650f7b8-2ff8-4084-acc6-cb0d6178e82e
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: b5ed2835-508b-4d72-aa69-f9754f9cd275
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: 'Menu settings'
        sortOrder: 3
      -
        elements:
          -
            style: tip
            tip: 'Use this for full width header banner'
            type: craft\fieldlayoutelements\Tip
          -
            fieldUid: 118e35c9-2543-4382-80aa-59987109b314
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Banner
        sortOrder: 4
handle: page
hasTitleField: true
name: Page
section: 7135d77d-f5e7-4d12-9d35-0c6e40777ee2
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
