fieldLayouts:
  0db58e3a-eaf4-49a0-a0aa-f82a909b5d7d:
    tabs:
      -
        elements:
          -
            fieldUid: 65aebe37-64ef-44f7-85e2-55b1788e8ebd
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 8a2aa11b-b2db-4cc2-9c6c-25d99ddb3913
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
      -
        elements:
          -
            fieldUid: 43321487-c0cf-4014-9c35-7d648822348c
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: SEO
        sortOrder: 2
      -
        elements:
          -
            fieldUid: e650f7b8-2ff8-4084-acc6-cb0d6178e82e
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: b5ed2835-508b-4d72-aa69-f9754f9cd275
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: 'Menu settings'
        sortOrder: 3
handle: resources
hasTitleField: true
name: Resources
section: ee1a1187-0557-4a96-a0a7-2fcebed07734
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
