fieldLayouts:
  b4e98168-e5e6-4ba5-8c20-d44fe110c893:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
handle: health
name: Health
siteSettings:
  3052e924-b84d-4d3c-a968-0df7f4320698:
    hasUrls: true
    template: _includes/featured_background
    uriFormat: 'health/{slug}'
structure:
  maxLevels: null
  uid: 79840a87-4613-4dc0-8f8b-30f0543bbed9
