fieldLayouts:
  2fa860f1-d5ba-4c80-8bc0-25cdcd5047e9:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
handle: supporters
name: Supporters
siteSettings:
  3052e924-b84d-4d3c-a968-0df7f4320698:
    hasUrls: true
    template: null
    uriFormat: 'supporters/{slug}'
structure:
  maxLevels: null
  uid: 951e1e8f-4c25-4ad8-a864-a1bc342bc445
