fieldLayouts:
  7c6761e0-cb08-4e0b-9e85-3dddb621a247:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            autofocus: false
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            required: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
handle: documents
hasUrls: true
name: Documents
settings:
  path: '@assetBasePath/documents'
sortOrder: 2
type: craft\volumes\Local
url: '@assetBaseUrl/documents'
