fieldLayouts:
  583e0ea0-3bba-4779-95f9-712c491b7836:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            autofocus: false
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            required: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
handle: pdfThumbs
hasUrls: true
name: 'PDf thumbs'
settings:
  path: '@assetBasePath/images/pdfthumbs'
sortOrder: 4
type: craft\volumes\Local
url: '@assetBaseUrl/images/pdfthumbs'
