fieldLayouts:
  704bb3fe-f4a2-4ed8-9a86-80a5a305d560:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            autofocus: false
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            required: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
handle: shipDocuments
hasUrls: true
name: 'Ship documents'
settings:
  path: '@assetBasePath/documents/ship'
sortOrder: 5
type: craft\volumes\Local
url: '@assetBaseUrl/documents/ship'
