fieldLayouts:
  448f8b73-aa14-40f1-807f-e30bb852d2ae:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            autofocus: false
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            required: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
handle: sponsorLogos
hasUrls: true
name: 'Sponsor logos'
settings:
  path: '@assetBasePath/images/sponsorslogos'
sortOrder: 3
type: craft\volumes\Local
url: '@assetBaseUrl/images/sponsorslogos'
