contentColumnType: string
fieldGroup: fc94dd78-cd02-4e18-9997-3618eef450de
handle: category
instructions: ''
name: Category
searchable: false
settings:
  allowLimit: false
  allowMultipleSources: false
  allowSelfRelations: false
  branchLimit: '2'
  limit: null
  localizeRelations: false
  selectionLabel: ''
  showSiteMenu: true
  source: 'group:c899c7ad-06e8-4e34-a6b3-72d0823a686a'
  sources: '*'
  targetSiteId: null
  validateRelatedElements: false
  viewMode: null
translationKeyFormat: null
translationMethod: site
type: craft\fields\Categories
