contentColumnType: string
fieldGroup: 21686fc5-b840-4187-b102-42cfc44b2948
handle: contentBlock
instructions: ''
name: 'Content block'
searchable: false
settings:
  contentTable: '{{%matrixcontent_contentblock}}'
  maxBlocks: ''
  minBlocks: ''
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
