contentColumnType: text
fieldGroup: ba782d24-db73-4ae4-8593-bfa7b9166f5c
handle: contactCategory
instructions: 'This is the Google analytics event action name for the contact category used to setup tracking of actions of contact submit and email contact link clicks'
name: 'Contact category'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: text
  initialRows: '4'
  multiline: ''
  placeholder: ''
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
