contentColumnType: text
fieldGroup: d435eef5-799f-4679-8343-ac26438416ca
handle: cookieDeny
instructions: 'If using the opt in or out type then this is the decline button text - defaults to ''Decline'''
name: 'Cookie deny button text'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: text
  initialRows: '4'
  multiline: ''
  placeholder: ''
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
