contentColumnType: string
fieldGroup: d435eef5-799f-4679-8343-ac26438416ca
handle: cookieType
instructions: ''
name: 'Cookie type'
searchable: false
settings:
  optgroups: true
  options:
    -
      __assoc__:
        -
          - label
          - Informational
        -
          - value
          - ''
        -
          - default
          - '1'
    -
      __assoc__:
        -
          - label
          - Opt-out
        -
          - value
          - opt-out
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Opt-in
        -
          - value
          - opt-in
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Dropdown
