contentColumnType: text
fieldGroup: d435eef5-799f-4679-8343-ac26438416ca
handle: cookieMessage
instructions: 'Appears in main bar on bottom'
name: 'Cookie message'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: text
  initialRows: '4'
  multiline: ''
  placeholder: 'This website uses cookies to ensure you get the best experience on our website. Declining cookies is fine'
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
