contentColumnType: text
fieldGroup: d435eef5-799f-4679-8343-ac26438416ca
handle: cookiePolicyLinkText
instructions: 'The text that links to learning more about cookies'
name: 'Cookie policy link text'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: text
  initialRows: '4'
  multiline: ''
  placeholder: ''
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
