contentColumnType: string
fieldGroup: 07d6c086-8295-48a4-ad25-f87ce9cf736a
handle: ctaBlock
instructions: 'Specifies settings for global cta block'
name: 'CTA Block'
searchable: false
settings:
  contentTable: '{{%matrixcontent_ctablock}}'
  maxBlocks: ''
  minBlocks: ''
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
