contentColumnType: string
fieldGroup: ce47295a-a3d8-4bcf-beec-283f57de4f52
handle: ctaButtonColor
instructions: ''
name: 'CTA button color'
searchable: false
settings:
  optgroups: true
  options:
    -
      __assoc__:
        -
          - label
          - Blue
        -
          - value
          - blue
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Blue-light
        -
          - value
          - blue-light
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Gray
        -
          - value
          - gray
        -
          - default
          - '1'
    -
      __assoc__:
        -
          - label
          - 'Gray light'
        -
          - value
          - gray-light
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Yellow
        -
          - value
          - yellow
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Dropdown
