contentColumnType: text
fieldGroup: ce47295a-a3d8-4bcf-beec-283f57de4f52
handle: ctaText
instructions: ''
name: 'CTA text'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: text
  initialRows: '4'
  multiline: ''
  placeholder: ''
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
