contentColumnType: text
fieldGroup: ce47295a-a3d8-4bcf-beec-283f57de4f52
handle: ctaTextShortVersion
instructions: 'used on mobile when we want it on one line :)'
name: 'CTA text short version'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: text
  initialRows: '4'
  multiline: ''
  placeholder: ''
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
