contentColumnType: text
fieldGroup: f7f618cd-8651-4d21-8055-18085e36d726
handle: customLink
instructions: ''
name: 'Custom link'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: text
  initialRows: '4'
  multiline: ''
  placeholder: ''
  uiMode: normal
translationKeyFormat: null
translationMethod: site
type: craft\fields\PlainText
