contentColumnType: text
fieldGroup: 82e59281-d6be-4eb2-adf5-853f9dc798d9
handle: documentLink
instructions: ''
name: 'Document link'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: text
  initialRows: '4'
  multiline: ''
  placeholder: ''
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
