contentColumnType: text
fieldGroup: eb93743b-bdd9-4aaf-8608-363189bbadbf
handle: featureTitle
instructions: ''
name: 'Feature title'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: false
  columnType: text
  initialRows: '4'
  multiline: ''
  placeholder: ''
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
