contentColumnType: boolean
fieldGroup: eb93743b-bdd9-4aaf-8608-363189bbadbf
handle: featureContent
instructions: 'Turn this on to make this content feature in its section'
name: 'Feature content'
searchable: false
settings:
  default: false
  offLabel: null
  onLabel: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
