contentColumnType: boolean
fieldGroup: fc94dd78-cd02-4e18-9997-3618eef450de
handle: featureFirstDocument
instructions: 'This is for multi layout adjustment - set this to yes to display a grid of thumbnails instead of a leading first document'
name: 'Feature first document'
searchable: false
settings:
  default: false
  offLabel: null
  onLabel: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
