contentColumnType: text
fieldGroup: e4c93e4d-84b8-421f-a362-6d1d686ec986
handle: footerFundersHeading
instructions: ''
name: 'Footer funders heading'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: text
  initialRows: '4'
  multiline: ''
  placeholder: 'We are grateful to our main funders for their continued support'
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
