contentColumnType: string
fieldGroup: e4c93e4d-84b8-421f-a362-6d1d686ec986
handle: footerfunders
instructions: 'Choose from sponsors list to add funders to the footer. This will pull in sponsor logo and website data automatically'
name: FooterFunders
searchable: false
settings:
  allowSelfRelations: false
  limit: ''
  localizeRelations: false
  selectionLabel: ''
  showSiteMenu: true
  source: null
  sources:
    - 'section:sponsors'
  targetSiteId: null
  validateRelatedElements: false
  viewMode: null
translationKeyFormat: null
translationMethod: site
type: craft\fields\Entries
