contentColumnType: text
fieldGroup: fc94dd78-cd02-4e18-9997-3618eef450de
handle: headingForOtherDocuments
instructions: ''
name: 'Heading for additional documents'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: text
  initialRows: '4'
  multiline: ''
  placeholder: ''
  uiMode: normal
translationKeyFormat: null
translationMethod: site
type: craft\fields\PlainText
