contentColumnType: boolean
fieldGroup: fc94dd78-cd02-4e18-9997-3618eef450de
handle: hideSponsorship
instructions: 'Turn this on to hide and remove sponsorship CTAs from this category of content'
name: 'Hide sponsorship'
searchable: false
settings:
  default: false
  offLabel: null
  onLabel: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
