contentColumnType: boolean
fieldGroup: b4462f20-6b0e-40a3-b91a-c71a2ef6d9d5
handle: hideSponsorshipCtaAndSponsors
instructions: 'Turn this on to hide CTAs and sponsorships'
name: 'Hide sponsorship cta and sponsors'
searchable: false
settings:
  default: false
  offLabel: null
  onLabel: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
