contentColumnType: boolean
fieldGroup: 21686fc5-b840-4187-b102-42cfc44b2948
handle: hidePage
instructions: 'Turn this on to hide page from display'
name: 'Hide page'
searchable: false
settings:
  default: false
  offLabel: null
  onLabel: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
