contentColumnType: boolean
fieldGroup: 1e257c82-5971-4f79-ba84-e4c0c92c6cc1
handle: hideBanner
instructions: ''
name: 'Hide banner'
searchable: false
settings:
  default: false
  offLabel: null
  onLabel: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
