contentColumnType: text
fieldGroup: 82e59281-d6be-4eb2-adf5-853f9dc798d9
handle: imageCredit
instructions: 'Add the author of the text'
name: 'Image credit'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: text
  initialRows: '4'
  multiline: ''
  placeholder: ''
  uiMode: normal
translationKeyFormat: null
translationMethod: language
type: craft\fields\PlainText
