contentColumnType: boolean
fieldGroup: 6a790902-45bf-469d-9d40-b12dd79fee3b
handle: initialSupporter
instructions: 'Turn this on on one sponsor only to centre that sponsor'
name: 'Initial supporter'
searchable: false
settings:
  default: false
  offLabel: null
  onLabel: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
