contentColumnType: string
fieldGroup: b4462f20-6b0e-40a3-b91a-c71a2ef6d9d5
handle: initialIndex
instructions: 'This chosen sponsor will appear in centre of carousel in footer'
name: 'Initial Sponsor'
searchable: false
settings:
  allowSelfRelations: false
  limit: '1'
  localizeRelations: false
  selectionLabel: 'Choose a sponsor to feature in footer centre'
  showSiteMenu: true
  source: null
  sources:
    - 'section:59d2222b-9f7b-433a-8efe-47caebb06702'
  targetSiteId: null
  validateRelatedElements: false
  viewMode: null
translationKeyFormat: null
translationMethod: site
type: craft\fields\Entries
