contentColumnType: text
fieldGroup: 82e59281-d6be-4eb2-adf5-853f9dc798d9
handle: media
instructions: ''
name: Media
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: text
  initialRows: '5'
  multiline: '1'
  placeholder: ''
  uiMode: normal
translationKeyFormat: null
translationMethod: language
type: craft\fields\PlainText
