contentColumnType: text
fieldGroup: ac95aba3-9fab-4eb8-b3cf-d21bf3e429dd
handle: menuTitle
instructions: ''
name: 'Menu title'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: ''
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
