contentColumnType: text
fieldGroup: bb607a26-226b-48b5-b616-dfa0583d8755
handle: newsIntro
instructions: ''
name: 'news intro'
searchable: false
settings:
  byteLimit: null
  charLimit: '200'
  code: ''
  columnType: text
  initialRows: '4'
  multiline: ''
  placeholder: ''
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
