contentColumnType: text
fieldGroup: 388af95c-9755-4484-8d28-6de30e4ae54a
handle: organisationName
instructions: ''
name: 'Organisation name'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: text
  initialRows: '4'
  multiline: ''
  placeholder: ''
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
