contentColumnType: string
fieldGroup: 70a4ac64-abe7-4301-99e0-99b3b5709e6e
handle: pdfDocument
instructions: ''
name: 'PDF document'
searchable: false
settings:
  allowSelfRelations: false
  allowUploads: true
  allowedKinds: null
  defaultUploadLocationSource: 'volume:528b0d00-159a-4866-aca8-d9394e99bb05'
  defaultUploadLocationSubpath: ''
  limit: ''
  localizeRelations: false
  previewMode: full
  restrictFiles: ''
  selectionLabel: ''
  showSiteMenu: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: true
  singleUploadLocationSource: 'volume:528b0d00-159a-4866-aca8-d9394e99bb05'
  singleUploadLocationSubpath: ''
  source: null
  sources:
    - 'volume:bccbe5e7-459a-476e-905c-a93ac10b478b'
  targetSiteId: null
  useSingleFolder: false
  validateRelatedElements: false
  viewMode: list
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
