contentColumnType: text
fieldGroup: 70a4ac64-abe7-4301-99e0-99b3b5709e6e
handle: publishersNames
instructions: ''
name: 'Publishers name(s)'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: false
  columnType: text
  initialRows: '4'
  multiline: ''
  placeholder: ''
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
