contentColumnType: boolean
fieldGroup: fc94dd78-cd02-4e18-9997-3618eef450de
handle: sendToSeafarerHelp
instructions: 'Turn this on to send this item to seafarerhelp ship resources via the API'
name: 'Send to seafarer help'
searchable: false
settings:
  default: true
  offLabel: null
  onLabel: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
