contentColumnType: text
fieldGroup: 4a21e974-ebcd-4857-ad8f-3183d7d0787e
handle: seo
instructions: ''
name: seo
searchable: false
settings:
  elementDisplayPreviewType: google
  facebookEnabledFields:
    - seoPreview
    - ogTitle
    - ogDescription
    - ogImage
  facebookTabEnabled: '1'
  generalEnabledFields:
    - seoPreview
    - seoTitle
    - seoDescription
    - seoImage
  generalTabEnabled: '1'
  sitemapEnabledFields:
    - sitemapUrls
  sitemapTabEnabled: '1'
  twitterEnabledFields:
    - seoPreview
    - twitterCardType
    - twitterTitle
    - twitterDescription
    - twitterImage
  twitterTabEnabled: '1'
translationKeyFormat: null
translationMethod: none
type: nystudio107\seomatic\fields\SeoSettings
