contentColumnType: boolean
fieldGroup: d435eef5-799f-4679-8343-ac26438416ca
handle: showCookieInfo
instructions: 'Turn on to show cookie message'
name: 'Show cookie info'
searchable: false
settings:
  default: false
  offLabel: null
  onLabel: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
