contentColumnType: string
fieldGroup: 6a790902-45bf-469d-9d40-b12dd79fee3b
handle: sponsorLogo
instructions: ''
name: 'Sponsor logo'
searchable: false
settings:
  allowSelfRelations: false
  allowedKinds: null
  defaultUploadLocationSource: 'volume:31305e73-ef23-400a-8aa0-c2d3efc27374'
  defaultUploadLocationSubpath: ''
  limit: ''
  localizeRelations: false
  restrictFiles: ''
  selectionLabel: ''
  showSiteMenu: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: true
  singleUploadLocationSource: 'volume:528b0d00-159a-4866-aca8-d9394e99bb05'
  singleUploadLocationSubpath: ''
  source: null
  sources:
    - 'volume:31305e73-ef23-400a-8aa0-c2d3efc27374'
  targetSiteId: null
  useSingleFolder: false
  validateRelatedElements: false
  viewMode: large
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
