contentColumnType: text
fieldGroup: 6a790902-45bf-469d-9d40-b12dd79fee3b
handle: sponsorsMessage
instructions: ''
name: 'Sponsors message'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: false
  columnType: text
  initialRows: '4'
  multiline: '1'
  placeholder: ''
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
