contentColumnType: text
fieldGroup: b4462f20-6b0e-40a3-b91a-c71a2ef6d9d5
handle: sponsoredByHeading
instructions: 'Title for a sponsored section'
name: 'Sponsored by heading'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: text
  initialRows: '4'
  multiline: ''
  placeholder: ''
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
