contentColumnType: text
fieldGroup: 6a790902-45bf-469d-9d40-b12dd79fee3b
handle: sponsorSelfTitle
instructions: 'The phrase the partner uses to describe their sponsorship relationship, eg "Premium Yachting partner"'
name: 'Sponsor self title'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: text
  initialRows: '4'
  multiline: ''
  placeholder: ''
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
