contentColumnType: text
fieldGroup: b4462f20-6b0e-40a3-b91a-c71a2ef6d9d5
handle: sponsorCTAButtonTitle
instructions: ''
name: 'Sponsor CTA button title'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: text
  initialRows: '4'
  multiline: ''
  placeholder: 'Sponsor this section'
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
