contentColumnType: text
fieldGroup: 6a790902-45bf-469d-9d40-b12dd79fee3b
handle: sponsorWebsiteUrl
instructions: ''
name: 'Sponsor website url'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: false
  columnType: text
  initialRows: '4'
  multiline: ''
  placeholder: ''
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
