contentColumnType: boolean
fieldGroup: bb607a26-226b-48b5-b616-dfa0583d8755
handle: sticky
instructions: 'turn this on to make news item stay on the top heading space'
name: Sticky
searchable: false
settings:
  default: false
  offLabel: null
  onLabel: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
