field: 670a426f-5790-4bb3-9041-04ae032d45c1
fieldLayouts:
  3b30b596-1b4d-4195-92ba-d1e3c57b9613:
    tabs:
      -
        elements:
          -
            fieldUid: 6e0ce7b7-9e83-4bdb-8190-14f14310c565
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  6e0ce7b7-9e83-4bdb-8190-14f14310c565:
    contentColumnType: text
    fieldGroup: null
    handle: item
    instructions: ''
    name: item
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: text
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
