field: 9f0c1a20-5b50-4304-b8bf-85f13791fe7a
fieldLayouts:
  e2765304-cbfb-4dff-91d7-0d3a5d84817e:
    tabs:
      -
        elements:
          -
            fieldUid: 093ea485-ea6b-45a5-b0be-109cd9d0fdd1
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 7426de1a-dca2-44bd-8654-d0527a326493
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 9ae6a315-2fa0-422e-a2d0-04974e9e4dcd
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: e189f6c2-029e-4fdb-9527-36dc28b8f579
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: a04cac6c-b190-4e7c-92a6-7737bb5600a8
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  093ea485-ea6b-45a5-b0be-109cd9d0fdd1:
    contentColumnType: string
    fieldGroup: null
    handle: icon
    instructions: ''
    name: Icon
    searchable: true
    settings:
      errorMessage: 'Unable to find component class ''plugins\dolphiq\iconpicker\fields\Iconpicker''.'
      expectedType: plugins\dolphiq\iconpicker\fields\Iconpicker
      settings:
        __assoc__:
          -
            - columnType
            - string
          -
            - iconFont
            - fontawesome-webfont
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\MissingField
  7426de1a-dca2-44bd-8654-d0527a326493:
    contentColumnType: text
    fieldGroup: null
    handle: text
    instructions: ''
    name: Text
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: text
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  9ae6a315-2fa0-422e-a2d0-04974e9e4dcd:
    contentColumnType: string
    fieldGroup: null
    handle: customIcon
    instructions: 'This will override icons chosen above. Remove it to use the font based icon'
    name: 'Custom icon'
    searchable: true
    settings:
      allowSelfRelations: false
      allowUploads: true
      allowedKinds: null
      defaultUploadLocationSource: 'volume:528b0d00-159a-4866-aca8-d9394e99bb05'
      defaultUploadLocationSubpath: ''
      limit: '1'
      localizeRelations: false
      previewMode: full
      restrictFiles: ''
      selectionLabel: ''
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: true
      singleUploadLocationSource: 'volume:528b0d00-159a-4866-aca8-d9394e99bb05'
      singleUploadLocationSubpath: ''
      source: null
      sources:
        - 'volume:customIcons'
      targetSiteId: null
      useSingleFolder: false
      validateRelatedElements: false
      viewMode: large
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  a04cac6c-b190-4e7c-92a6-7737bb5600a8:
    contentColumnType: string
    fieldGroup: null
    handle: iconSize
    instructions: ''
    name: 'Icon size'
    searchable: true
    settings:
      optgroups: true
      options:
        -
          __assoc__:
            -
              - label
              - 1x
            -
              - value
              - fa-1x
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 2x
            -
              - value
              - fa-2x
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 3x
            -
              - value
              - fa-3x
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 4x
            -
              - value
              - fa-4x
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 5x
            -
              - value
              - fa-5x
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 6x
            -
              - value
              - fa-6x
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 7x
            -
              - value
              - fa-7x
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 8x
            -
              - value
              - fa-8x
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 9x
            -
              - value
              - fa-9x
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 10x
            -
              - value
              - fa-10x
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
  e189f6c2-029e-4fdb-9527-36dc28b8f579:
    contentColumnType: string(7)
    fieldGroup: null
    handle: iconColor
    instructions: ''
    name: 'Icon color'
    searchable: true
    settings:
      defaultColor: '#ffffff'
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Color
