field: b3cdf578-7f9a-4376-94f1-b87e9e24c41c
fieldLayouts:
  d04edb13-dd90-4c90-9f4e-a8de24ca5d29:
    tabs:
      -
        elements:
          -
            fieldUid: f35d2165-a747-407e-ac92-866bb9e2bde9
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  f35d2165-a747-407e-ac92-866bb9e2bde9:
    contentColumnType: text
    fieldGroup: null
    handle: tickItem
    instructions: ''
    name: 'Tick item'
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: text
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
