fieldLayouts:
  85aebb7f-2279-4e59-98bb-ef14d05af5bf:
    tabs:
      -
        elements:
          -
            fieldUid: 4d97bb57-65e2-4a24-a25f-de74c14bb806
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 39cb28b0-c735-434f-9b08-3fa2fb9181da
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: ac591f65-95a6-4475-93d1-e7420a09d3b7
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 2691c7ac-516d-4909-a877-c3075919238c
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: 'Footer links & copyright'
        sortOrder: 1
handle: copyright
name: Copyright
