fieldLayouts:
  4a976436-33be-4611-850b-3cb61783c35e:
    tabs:
      -
        elements:
          -
            fieldUid: e74c291e-df7d-48c0-8ac9-e5f31884e718
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: b620b7ae-6825-4bcd-86f3-46d1f8b9a7f8
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 40749053-27f4-42fb-a2e2-06d699959fbf
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 500c4a94-e40d-4ee8-aebd-aff3570a9d88
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 418e2fe7-63c7-498f-917d-7f01386f0f71
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 35c8638d-ca7a-4396-acab-1e6f328c116d
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 206a7b8d-a09f-47e4-b472-5d0c046d9105
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
handle: donate
name: Donate
