fieldLayouts:
  c5c702eb-58bc-471f-bc63-d46afd9857ae:
    tabs:
      -
        elements:
          -
            fieldUid: 8c74c5ae-bf1a-4b25-af8a-e3495afbbf74
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 092a7f40-a254-4f2d-8173-b70bd1dfee2d
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 555a43ff-93fe-46ef-866a-725644f9e387
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 36f6766e-e188-4d25-9161-9c673db5c821
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: 'Global contact'
        sortOrder: 1
handle: organisationDetails
name: 'Organisation details'
