fieldLayouts:
  0ef9f90b-db42-4409-a34b-8980b40767d9:
    tabs:
      -
        elements:
          -
            fieldUid: 9b862d5f-8e3b-4cdf-ac1f-05d4395496ef
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: bded12f3-39fd-4478-9b21-048e259e9655
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 18b726f6-1d79-424b-b312-83aa0270dd29
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: 'Global contact'
        sortOrder: 1
handle: organisationDetails
name: 'Organisation details'
