fieldLayouts:
  fa9d652f-9236-43e5-b194-23a0258cdfaa:
    tabs:
      -
        elements:
          -
            fieldUid: b2ea93f7-39b1-45fc-8bd8-028340e3ccd6
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: c4f8eadf-f0c0-4cef-b198-00fb9eb0deec
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: c8a0cc25-0bc9-4906-bb91-0f55e69cefc9
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 9113b4e5-c9db-40b7-8b9d-f161272c680c
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: 'Global site info'
        sortOrder: 1
handle: siteInfo
name: 'Site info'
