fieldLayouts:
  f90711d0-49ea-4bef-b70f-ea4cb8c72eee:
    tabs:
      -
        elements:
          -
            fieldUid: 43f404b9-0e0c-40db-8142-11358b6f7a4b
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: ce6e4893-59fa-4d19-921d-fefd5afa325f
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: e1491df8-599d-4eac-8685-3fed68822e28
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: 'Global site info'
        sortOrder: 1
handle: siteInfo
name: 'Site info'
