fieldLayouts:
  be206ea8-dcd7-408e-9382-db8a0d04c777:
    tabs:
      -
        elements:
          -
            fieldUid: d82c2d1c-e521-4dc3-91e9-9a605859ccda
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: d5deeb9d-4ca1-458a-8271-ac30270cd7f7
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 457b4ecf-b7f5-4786-829a-89d0b56cdbcf
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: e6f67900-50ba-4d01-b0bb-357158f78857
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: c5f8a4c6-48a6-4ecd-be9d-e70d53f3e17c
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: 'Social links'
        sortOrder: 1
handle: social
name: Social
