fieldLayouts:
  3561f55b-d310-4ac1-ac81-75677169e94a:
    tabs:
      -
        elements:
          -
            fieldUid: 30f69f73-a8e3-4862-8bf4-095dccd0c543
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 1db79d86-3c6a-4ab8-af8e-f545af173786
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 35c85561-4388-4ade-8076-b12aa08b7aa2
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 40c475e0-a837-4c63-98fe-c5e39febf18d
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: bb9c5da5-0477-42ad-9c0c-245f02f419fb
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: 'Social links'
        sortOrder: 1
handle: social
name: Social
