fieldLayouts:
  8e5b5cd8-2387-4c3c-9dc1-adf1ec61ad68:
    tabs:
      -
        elements:
          -
            fieldUid: 24298ad4-3c22-4c09-9418-d14376c56e83
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: d68a619f-16d3-40a8-b289-2994d3ab886d
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 2d51d1ce-0fbe-427c-a24d-79c785b65d0f
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 1bdbfbdb-86ab-4c61-8db7-793e3bc3a57a
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: e3033f39-d913-434c-8a2f-9845a1299184
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: e2a6cc0f-6960-4a95-90fa-365487588264
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 757de41c-a9d1-49f3-bd3e-8b6cd6476511
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 8040399e-55a2-4b37-9981-bb5d96273241
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: 'Global sponsor settngs'
        sortOrder: 1
handle: sponsorSettings
name: 'Sponsor settings'
