fieldLayouts:
  57eee618-4027-4b46-910f-e1d1aaddbe6c:
    tabs:
      -
        elements:
          -
            fieldUid: 03e79f6c-078d-4f55-a010-5a69c873c392
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: b84435db-37fd-4264-943e-fadaa7fc1814
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: e74c291e-df7d-48c0-8ac9-e5f31884e718
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: b620b7ae-6825-4bcd-86f3-46d1f8b9a7f8
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 418e2fe7-63c7-498f-917d-7f01386f0f71
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 500c4a94-e40d-4ee8-aebd-aff3570a9d88
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 206a7b8d-a09f-47e4-b472-5d0c046d9105
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 35c8638d-ca7a-4396-acab-1e6f328c116d
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 199058a2-e5b9-48c8-bb58-af2d3f89bfbc
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: 'Global sponsor settngs'
        sortOrder: 1
handle: sponsorSettings
name: 'Sponsor settings'
