fieldLayouts:
  e8dd5db7-fb98-44f5-9a68-3f020c805897:
    tabs:
      -
        elements:
          -
            fieldUid: 3602008c-51bc-4606-a5df-b450478a0c04
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: 'Tracking scripts'
        sortOrder: 1
handle: tracking
name: Tracking
