enableVersioning: true
handle: mainMenu
name: 'Main menu'
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
propagationMethod: all
siteSettings:
  3052e924-b84d-4d3c-a968-0df7f4320698:
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
structure:
  maxLevels: null
  uid: 737aff34-aecd-479f-a884-e3ecb1e999c0
type: structure
