enableVersioning: true
handle: news
name: News
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
propagationMethod: all
siteSettings:
  3052e924-b84d-4d3c-a968-0df7f4320698:
    enabledByDefault: true
    hasUrls: true
    template: news/_entry
    uriFormat: 'news/{postDate.year}/{slug}'
type: channel
