enableVersioning: true
handle: resources
name: Resources
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
propagationMethod: all
siteSettings:
  3052e924-b84d-4d3c-a968-0df7f4320698:
    enabledByDefault: true
    hasUrls: true
    template: pages/_entry.twig
    uriFormat: 'resources/{slug}'
structure:
  maxLevels: null
  uid: 908dea89-97ea-4951-ba8c-86e78de1fa59
type: structure
